# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true

  push:
    desc: commit and pushes current changes
    cmds:
      - git add .  || true
      - git commit -am "$(curl -s https://commit.cacko.net/index.txt)" || true
      - git push || true

  build:
    desc: build
    cmds:
      - git clean -xdf
      - rm -rf dist/*
      - python setup.py bdist_wheel

  publish:
    desc: publish
    cmds:
      - scp dist/* muzak:/var/www/pypi/packages/gender_predictor

  deploy:
    desc: all
    cmds:
      - task: push
      - task: build
      - task: publish
